# Generated by Django 3.2.6 on 2021-08-11 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_contactmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='edited_date',
            new_name='updated_date',
        ),
    ]
