from .contact import contact
from .index import index
from .category import CategoryListView
from .my_posts import my_posts
from .detail import DetailView
from .add_post import AddPostCreateView
from .edit_post import PostUpdateView   
from .delete_post import DeletePostView
from .delete_comment import delete_comment
