# Generated by Django 3.2.6 on 2021-08-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_postmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postmodel',
            table='Post',
        ),
    ]
